kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: east
nodes:
- role: control-plane
  labels:
    topology.kubernetes.io/region: east
    topology.kubernetes.io/zone: zone1
- role: worker
  labels:
    topology.kubernetes.io/region: east
    topology.kubernetes.io/zone: zone1
- role: worker
  labels:
    topology.kubernetes.io/region: east
    topology.kubernetes.io/zone: zone2
