kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: west
nodes:
- role: control-plane
  labels:
    topology.kubernetes.io/region: west
    topology.kubernetes.io/zone: zone3
- role: worker
  labels:
    topology.kubernetes.io/region: west
    topology.kubernetes.io/zone: zone3
