apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: import-echo-server
  namespace: istio-system
spec:
  hosts:
  - httpbin.global.mesh
  ports:
  - number: 8000
    name: http
    protocol: HTTP
  endpoints:
{{- if .Values.eastwestEgressEnabled }}
  - address: {{ $.Values.egressGatewayIP }}
{{- else }}
  - address: {{ $.Values.eastwestGatewayIP }}
{{- end }}
    ports:
      http: 15443
    network: west-network
    locality: west
    labels:
      security.istio.io/tlsMode: istio
  location: MESH_INTERNAL
  resolution: STATIC
---
{{- if $.Values.eastwestEgressEnabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-eastwestgateway-egress
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway-egress
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    hosts:
    - "httpbin.global.mesh"
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cross-network-egress
  namespace: istio-system
spec:
  hosts:
  - "*.global.mesh"
  gateways:
  - istio-eastwestgateway-egress
  tls:
  - match:
    - sniHosts:
      # This rule matches Istio mTLS SNI format, i.e. outbound_.<port>_.<subset>_.<hostname>
      - "*.global.mesh"
    route:
    - destination:
        host: ingress.remote-mesh.global
        port:
          number: 15443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ingress-remote-mesh
  namespace: istio-system
spec:
  exportTo:
  - "."
  hosts:
  - ingress.remote-mesh.global
  ports:
  - number: 15443
    name: auto-passthrough-tls
    protocol: TLS
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: {{ $.Values.eastwestGatewayIP }}
    ports:
      auto-passthrough-tls: 15443
    network: west-network
    locality: west
{{- end }}
