apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: import-echo-server
  namespace: istio-system
spec:
  hosts:
  - httpbin.global.mesh
  ports:
  - number: 8000
    name: http
    protocol: HTTP
  endpoints:
  - address: {{ $.Values.eastwestGatewayIP }}
    ports:
      http: 15443
    network: west-network
    locality: west
    labels:
      security.istio.io/tlsMode: istio
  location: MESH_INTERNAL
  resolution: STATIC
