---
name: Check .md links

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  markdown-link-check-periodic:
    name: Markdown Links (all files)
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Checks the status of hyperlinks in .md files
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          config-file: ".mdlinkcheck.json"
          folder-path: "docs/common, docs/multicluster"

      - name: Raise an Issue to report broken links
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd
        with:
          title: Broken link detected by CI
          content-filepath: .github/ISSUE_TEMPLATE/broken-link.md
          labels: automated, broken link
